### ISSUE TITLE
i cant get it to work 

### ISSUE THREAD

**Issue by Johvu** [jonassvensson4/jsfour-core#2]
so I reinstalled yarn and then installed through npm still i cant get it to work

**Comment by jnsvns** [comment]
Can't get what to work? Are you getting any errors?

You can't just create an issue that says "i cant get it to work"..

**Comment by Johvu** [comment]
its saying Building resource jsfour-core failed.
                 Error data: yarn failed!

**Comment by jnsvns** [comment]
If you're installing it manually you'll have to remove yarn from the __resource.lua since it's a dependency

**Comment by Johvu** [comment]
Thank i got it working
