### ISSUE TITLE
Cannot enable jsfour-mdc

### ISSUE THREAD

**Issue by ghost** [jonassvensson4/jsfour-core#3]
jsfour-core is working and functional i am recieving error messages in logas follows

![image](https://user-images.githubusercontent.com/44256030/69776706-63f4ce80-11f1-11ea-9778-b214b8d8539c.png)

please advise

**Comment by jnsvns** [comment]
jsfour-mdc has nothing to do with jsfour-core.

I can't even see an error from the jsfour-mdc resource? If you look to the left you can clearly see that it's "locksystem" and "interactsound" that gives you the errors? So I'm not sure why you're opening an issue in my repo. Contact the authors of the other resources.
