### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by thefrcrazy** [jonassvensson4/jsfour-core#4]
I have all installed manually and nothing works I have this problem and I have the "server.js" which does not load
![Screenshot_34](https://user-images.githubusercontent.com/37953895/71781775-c3a17f00-2fd2-11ea-8740-e45aecddf4e4.png)
![Screenshot_35](https://user-images.githubusercontent.com/37953895/71781777-c603d900-2fd2-11ea-93d1-48d81d2a4796.png)

**Comment by jnsvns** [comment]
Resource has been recoded, should work fine now.
