### ISSUE TITLE
 [JSFOUR-REGISTER] Issue with the new FXv2

### ISSUE THREAD

**Issue by Alevhovic** [jonassvensson4/jsfour-core#6]
Hello Jonas,

Thirst, i really want to thank you for all the works you shared, we use you ID-CARD script and your REGISTER script too.

I try to update the `__resource.lua` with the new `fxmanifest.lua` and the script doesn't work anymore (people are in the sky, without any UI).

The line : 
**__resource.lua** 
`resource_type 'map' { gameTypes = { fivem = true } }`

Is not valid anymore, with the new FXv2. Because fiveM add a folder named `basic-gamemode` and i think he totally ruin your lovelly script **jsfour-register**...

The stuff i try : 

- Remove `basic-gamemode` = In prompt : "**couldn't load resource fivem..**" = Serveur doesn't start.
 
- Change the line :
`resource_type 'gametype' { name = 'Freeroam' }`
in the `basic-addon`, file : `fxmanifest.lua` by :
`resource_type 'gametype' { name = 'fivem' }`

- And : 
`resource_type 'map' { gameTypes = { ['fivem'] = true } }`

- And :
`resource_type 'map' { gameTypes = { ['basic-gamemode'] = true } }` (why not, but i know before is not going to work x) ).

I see you updating some resources with the new `fxmanifest.lua`, maybe you know how to continue to use your script with the new FXv2...

Thank to you, and i'm really sorry about writing an issue here.

**Comment by jnsvns** [comment]
I have no idea how the new resource_type works. 

The jsfour-register has been archived and that's why you can't create any issues in that repo. I have no plans on getting back to that resource. I'm sorry but I can't help you.
